//! ActionModel — Embodied Action Closure (Component 7)
//!
//! Closes the perception-action loop: at each step, actual `WorldFeedback`
//! is compared to the previous-step prediction (generated by `select_and_predict`),
//! yielding `action_pred_err`. A new policy is then selected by argmax of
//! the active inference posterior, and the corresponding observation prior is
//! stored as the next-step prediction.
//!
//! `action_pred_err` is tracked via EMA and written to register 30
//! (`meta_error_corr`) by `Being32::step_action_model`. It is NOT injected
//! into `app_pred_err` in v1.5.1 (backward compat with CMAP A–F). Deferred to v1.6.0.

const ACTION_EMA_ALPHA: f32 = 0.02;

pub const APPROACH: usize = 0;
pub const AVOID: usize = 1;
pub const FREEZE: usize = 2;

const PRIORS: [[f32; 3]; 3] = [
    [0.7, 0.1, 0.7],
    [0.1, 0.7, 0.1],
    [0.3, 0.3, 0.3],
];

#[derive(Clone, Debug)]
pub struct ActionModel {
    pub priors: [[f32; 3]; 3],
    pub last_policy: usize,
    pub predicted_fb: [f32; 3],
    pub action_pred_err: f32,
    pub ema_action_pred_err: f32,
}

impl ActionModel {
    pub fn new() -> Self {
        Self {
            priors: PRIORS,
            last_policy: APPROACH,
            predicted_fb: PRIORS[APPROACH],
            action_pred_err: 0.0,
            ema_action_pred_err: 0.0,
        }
    }

    pub fn observe(&mut self, reward: f32, threat: f32, contact: f32) {
        let dr = reward - self.predicted_fb[0];
        let dt = threat - self.predicted_fb[1];
        let dc = contact - self.predicted_fb[2];
        self.action_pred_err = ((dr * dr + dt * dt + dc * dc) / 3.0).sqrt().min(1.0);
        self.ema_action_pred_err += ACTION_EMA_ALPHA * (self.action_pred_err - self.ema_action_pred_err);
    }

    pub fn select_and_predict(&mut self, policy_posterior: [f32; 3]) {
        let mut best = 0;
        for i in 1..3 {
            if policy_posterior[i] > policy_posterior[best] { best = i; }
        }
        self.last_policy = best;
        self.predicted_fb = self.priors[best];
    }

    pub fn is_calibrated(&self) -> bool { self.ema_action_pred_err < 0.3 }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zero_error_when_prediction_matches() {
        let mut m = ActionModel::new();
        m.observe(0.7, 0.1, 0.7);
        assert!(m.action_pred_err < 1e-5, "err={}", m.action_pred_err);
    }

    #[test]
    fn max_error_on_opposite_outcome() {
        let mut m = ActionModel::new();
        m.observe(0.0, 1.0, 0.0);
        let expected = ((0.49_f32 + 0.81 + 0.49) / 3.0).sqrt();
        assert!((m.action_pred_err - expected).abs() < 1e-4,
            "err={} expected≈{}", m.action_pred_err, expected);
    }

    #[test]
    fn policy_selection_picks_highest_posterior() {
        let mut m = ActionModel::new();
        m.select_and_predict([0.1, 0.8, 0.1]);
        assert_eq!(m.last_policy, AVOID);
        assert_eq!(m.predicted_fb, PRIORS[AVOID]);
    }

    #[test]
    fn ema_converges_to_steady_error() {
        let mut m = ActionModel::new();
        for _ in 0..200 { m.observe(0.0, 0.0, 0.0); }
        let expected_err = ((0.49_f32 + 0.01 + 0.49) / 3.0).sqrt();
        assert!((m.ema_action_pred_err - expected_err).abs() < 0.05,
            "ema={} expected≈{}", m.ema_action_pred_err, expected_err);
    }
}
